### ISSUE TITLE
Importer doesn't work on macOS

### ISSUE THREAD

**Issue by drd-dev** [NicMagnier/PlaydateLDtkImporter#16]
There seems to be an issue with the importer on macOS, when attempting to load a JSON level, I get the following error. I believe this is to do with the Mac's filesystem. Running the exact same codebase on windows 11 causes zero issues.

![image](https://github.com/NicMagnier/PlaydateLDtkImporter/assets/16552473/4e15f12f-a9fa-4aa1-b379-bda9cbe92e82)

Currently on macOS 13.4.1 running on an M2 chip.

**Comment by NicMagnier** [comment]
I develop the importer on a Mac so the problem probably doesn't come from it.
The error is triggered either because the file does not exist or the SDK cannot decode the file.

Can you send the ldtk file so I can check?

**Comment by drd-dev** [comment]
I think the issue must have been with the ldtk file. I remade it from scratch, and everything worked after that.
