### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nickzman** [NicMagnier/PlaydateLDtkImporter#9]
I'd like to use this in a project, but I see nothing in the repository about licensing - no LICENSE file, no license assigned to the project, no license in the source code, nothing. Without a license, I don't know whether I'm legally allowed to use this in a game or not, or how I'm allowed to use it.

How is this code licensed to third-party developers? Can you please add licensing information to this repository? Thanks!

**Comment by nickzman** [comment]
@NicMagnier , are you there? Can you please set a license for this project so I & others will understand how this code is licensed to us? Thanks.

**Comment by paulstraw** [comment]
@NicMagnier thank you for this very useful project. I hate to be a bumper, but my game is getting closer to release and I've finished adding all the required licenses on the about screen except this one!

Edit: For anyone curious on why this matters, here's what a [GitHub-curated license info site](https://choosealicense.com/no-permission/) has to say about it:

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

**Comment by nickzman** [comment]
Thank you! I appreciate your work on this.
